resources:
  - git
  - slack
  - github
  - website
  - gitee
  - download
  - namespace.yaml
  - gitee-star
  - collect-data
  - gitee-event
  - report-email
  - meetings
  - polymerization
  - polymerization-download
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: openlookeng-om
