resources:
  - git
  - src-git
  - gitee
  - github
  - website
  - cloudeye
  - maillist
  - namespace.yaml
  - gitee-star
  - collect-data
  - gitee-event
  - report-email
  - meetings
  - cla
  - website-repo
  - website-ru-repo
  - cve
  - polymerization
  - polymerization-download
  - polymerization-download-ip
  - account_org
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: openeuler-om
