kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: b08cdf56-c841-4866-b276-40b4bc8ab025
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
spec:
  #We need set this into 'Local' since we need get the client IP of elb.
  externalTrafficPolicy: Local
