resources:
  - ../../../common-services/etherpad
  - ingress.yaml
  - secrets.yaml
  - namespace.yaml
commonLabels:
  app: control-etherpad
commonAnnotations:
  owner: tommylike
  email: "tommylikehu@gmail.com"
patchesStrategicMerge:
  - configmap.yaml
  - pvc.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: etherpad-lite
    path: remove-traffic-strategy.yaml
namespace: etherpad
