resources:
  - ingress.yaml
  - mailman.yaml
  - namespace.yaml
  - secrets.yaml
  - nginx-purger.yaml
commonLabels:
  app: osinfra-api
commonAnnotations:
  owner: tommylike
  email: "tommylikehu@gmail.com"
namespace: osinfra-api

