apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mailmanweb-ingress-for-osinfra
spec:
  tls:
    - hosts:
        - mailweb.osinfra.cn
      secretName: mailman-cert-secrets
  rules:
    - host: mailweb.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: mailman-web-service
              servicePort: 80
            path: /
