resources:
  - config.yaml
  - mailcore.yaml
  - mailcoreservice.yaml
  - mtaservice.yaml
  - namespace.yaml
  - nginx-config.yaml
  - secrets.yaml
  - storage.yaml
  - suiteservice.yaml
  - webservice.yaml
  - ingress.yaml
commonAnnotations:
  owner: tommylike
  email: "tommylikehu@gmail.com"
namespace: mail
commonLabels:
  solution: control-maillist
