resources:
  - git
  - github
  - website
  - gitee
  - download
  - package
  - blog
  - namespace.yaml
  - gitee-star
  - collect-data
  - gitee-event
  - report-email
  - meetings
  - cla
  - polymerization
  - polymerization-download
  - account_org
  - git_commit
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: opengauss-om
