resources:
  - git
  - github
  - website
  - website-ascend
  - gitee
  - download
  - namespace.yaml
  - collect-data
  - gitee-event
  - gitee-star
  - report-email
  - meetings
  - cla
  - polymerization
  - polymerization-download
  - polymerization-download-ip
  - account_org
commonAnnotations:
  owner: zhongjun
  email: "jun.zhongjun2@gmail.com"
namespace: mindspore-om
