apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  30099: "repo-thirdparty/mindspore-service:22"
  30022: "download/repo-service:22"
  31873: "repo-thirdparty/mindspore-service:873"
  30873: "download/repo-service:873"
  50000: "jenkins-master/mindspore-jenkins:50000"
