apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: basic-auth
spec:
  name: basic-auth
  keysMap:
    auth:
      path: secrets/data/infra-common/prometheus/mindspore-cn-north4
      key: basic-auth
