resources:
  - ../../../../../common-services/om
patches:
  - path: deploy.json
    target:
      group: extensions
      version: v1beta1
      kind: Deployment
      name: om-collect
patchesStrategicMerge:
  - secrets.yaml
images:
  - name: swr.cn-north-4.myhuaweicloud.com/om/om-collect
    newName: swr.cn-north-4.myhuaweicloud.com/om/om-collection
    newTag: 0.0.20
namePrefix: collect-data-
