resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
  - ingress.yaml
commonLabels:
  app: common-jenkins
commonAnnotations:
  owner: tommylike
  email: "tommylikehu@gmail.com"
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
namespace: jenkins
